package Classes;
// Generated 05/07/2014 23:51:54 by Hibernate Tools 3.6.0



/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private Integer codEnd;
     private String logradouro;
     private String bairro;
     private String cidade;
     private int numero;
     private String estado;

    public Endereco() {
    }

    public Endereco(String logradouro, String bairro, String cidade, int numero, String estado) {
       this.logradouro = logradouro;
       this.bairro = bairro;
       this.cidade = cidade;
       this.numero = numero;
       this.estado = estado;
    }
   
    public Integer getCodEnd() {
        return this.codEnd;
    }
    
    public void setCodEnd(Integer codEnd) {
        this.codEnd = codEnd;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Override
    public String toString() {
        return logradouro + ", " + numero + ", " + bairro + ", " + cidade + ", " + estado;
    }




}


