package Classes;
// Generated 05/07/2014 23:51:54 by Hibernate Tools 3.6.0

import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;




/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private Integer codEnd;
     private String logradouro;
     private String bairro;
     private String cidade;
     private int numero;
     private String estado;

    public Endereco() {
    }

    public Endereco(String logradouro, String bairro, String cidade, int numero, String estado) {
       this.logradouro = logradouro;
       this.bairro = bairro;
       this.cidade = cidade;
       this.numero = numero;
       this.estado = estado;
    }
   
    public Integer getCodEnd() {
        return this.codEnd;
    }
    
    public void setCodEnd(Integer codEnd) {
        this.codEnd = codEnd;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public void cadastrar(){
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            session.save(this);
            session.getTransaction().commit();
            //HibernateUtil.shutdown();
            Mensagem msg = new Mensagem("cadastrado","Endereco",this.toString());
            msg.sucesso();
        } catch (Exception erro) {
            Mensagem msg = new Mensagem("cadastro","Endereco",erro.getMessage());
            msg.erro();
            //erro.printStackTrace();
        }
    }
    public void excluir(){
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            session.delete(this);
            session.getTransaction().commit();
            //HibernateUtil.shutdown();
            Mensagem msg = new Mensagem("excluido","Endereco",this.toString());
            msg.sucesso();
        } catch (Exception erro) {
            Mensagem msg = new Mensagem("exclusão","Endereco",erro.getMessage());
            msg.erro();
            //erro.getMessage();
        }
    }
    public void editar(){
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            session.update(this);
            session.getTransaction().commit();
            //HibernateUtil.shutdown();
            Mensagem msg = new Mensagem("editado","Endereco",this.toString());
            msg.sucesso();
        } catch (Exception erro) {
            Mensagem msg = new Mensagem("edição","Endereco",erro.getMessage());
            msg.erro();
            //erro.getMessage();
        }
    }
    public DefaultTableModel modelo(javax.swing.JTable jTable1){
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query select = session.createQuery("from Endereco");  
        List lista = select.list();  
        session.getTransaction().commit();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Fabricante fab;
        model.setNumRows(0);
        for (int i = 0; i<lista.size();i++){
            fab = (Fabricante) lista.get(i);
            String[] data = new String[2];
            data[0] = String.valueOf(fab.getCodFabricante());
            data[1] = fab.getNome();
            model.addRow(data);
            System.out.println(data);
        }
        return model;
    }
    
    @Override
    public String toString() {
        return logradouro + ", " + numero + ", " + bairro + ", " + cidade + ", " + estado;
    }




}


