package Classes;
// Generated 05/07/2014 23:51:54 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Manutencao generated by hbm2java
 */
public class Manutencao  implements java.io.Serializable {


     private Integer codManut;
     private String descricaoProblema;
     private Date dataM;
     private String solucao;

    public Manutencao() {
    }

    public Manutencao(String descricaoProblema, Date dataM, String solucao) {
       this.descricaoProblema = descricaoProblema;
       this.dataM = dataM;
       this.solucao = solucao;
    }
   
    public Integer getCodManut() {
        return this.codManut;
    }
    
    public void setCodManut(Integer codManut) {
        this.codManut = codManut;
    }
    public String getDescricaoProblema() {
        return this.descricaoProblema;
    }
    
    public void setDescricaoProblema(String descricaoProblema) {
        this.descricaoProblema = descricaoProblema;
    }
    public Date getDataM() {
        return this.dataM;
    }
    
    public void setDataM(Date dataM) {
        this.dataM = dataM;
    }
    public String getSolucao() {
        return this.solucao;
    }
    
    public void setSolucao(String solucao) {
        this.solucao = solucao;
    }




}


