package Classes;
// Generated 05/07/2014 23:51:54 by Hibernate Tools 3.6.0

import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;




/**
 * TipoEquipamento generated by hbm2java
 */
public class TipoEquipamento  implements java.io.Serializable {


     private Integer codTipo;
     private String nomeTipoEquip;
     private String descricao;

    public TipoEquipamento() {
    }

    public TipoEquipamento(String nomeTipoEquip, String descricao) {
       this.nomeTipoEquip = nomeTipoEquip;
       this.descricao = descricao;
    }
   
    public Integer getCodTipo() {
        return this.codTipo;
    }
    
    public void setCodTipo(Integer codTipo) {
        this.codTipo = codTipo;
    }
    public String getNomeTipoEquip() {
        return this.nomeTipoEquip;
    }
    
    public void setNomeTipoEquip(String nomeTipoEquip) {
        this.nomeTipoEquip = nomeTipoEquip;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public void cadastrar(){
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            session.save(this);
            session.getTransaction().commit();
            //HibernateUtil.shutdown();
            Mensagem msg = new Mensagem("cadastrado","Tipo de Equipamento",this.toString());
            msg.sucesso();
        } catch (Exception erro) {
            Mensagem msg = new Mensagem("cadastro","Tipo de Equipamento",erro.getMessage());
            msg.erro();
            //erro.printStackTrace();
        }
    }
    public void excluir(){
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            session.delete(this);
            session.getTransaction().commit();
            //HibernateUtil.shutdown();
            Mensagem msg = new Mensagem("excluido","Tipo de Equipamento",this.toString());
            msg.sucesso();
        } catch (Exception erro) {
            Mensagem msg = new Mensagem("exclusão","Tipo de Equipamento",erro.getMessage());
            msg.erro();
            //erro.getMessage();
        }
    }
    public void editar(){
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            session.update(this);
            session.getTransaction().commit();
            //HibernateUtil.shutdown();
            Mensagem msg = new Mensagem("editado","Tipo de Equipamento",this.toString());
            msg.sucesso();
        } catch (Exception erro) {
            Mensagem msg = new Mensagem("edição","Tipo de Equipamento",erro.getMessage());
            msg.erro();
            //erro.getMessage();
        }
    }
    public DefaultTableModel modelo(javax.swing.JTable jTable1){
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query select = session.createQuery("from TipoEquipamento");  
        List lista = select.list();  
        session.getTransaction().commit();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        TipoEquipamento fab;
        model.setNumRows(0);
        for (int i = 0; i<lista.size();i++){
            fab = (TipoEquipamento) lista.get(i);
            String[] data = new String[2];
            data[0] = String.valueOf(fab.getCodTipo());
            data[1] = fab.getNomeTipoEquip();
            data[2] = fab.getDescricao();
            model.addRow(data);
            System.out.println(data);
        }
        return model;
    }

    @Override
    public String toString() {
        return nomeTipoEquip + ", " + descricao;
    }




}


